#include <Wire.h>

#define ACCELEROMETER 0x53

#define BUZZER 11
#define MOW    14
#define MOTOR1_FWD 3
#define MOTOR1_BWD 4
#define MOTOR1_SPEED 5
#define MOTOR2_FWD 7
#define MOTOR2_BWD 8
#define MOTOR2_SPEED 6
#define START 9
#define HOME 10
#define ON_RED 12
#define ON_GREEN 13
#define SENSOR_R A3
#define SENSOR_L A2
#define TAP 2

#define TILT_Y -200

#define STATUS_BOOT  0
#define STATUS_ALARM 1
#define STATUS_RESETTABLE_ALARM 2
#define STATUS_IDLE 3
#define STATUS_IDLE_READY  4
#define STATUS_ILIKETOMOWIT_IDLE 5
#define STATUS_ILIKETOMOWIT_ENTER 6
#define STATUS_ILIKETOMOWIT_WAITMOW 7
#define STATUS_ILIKETOMOWIT_WAIT2  8
#define STATUS_ILIKETOMOWIT 9


#define MAX_SPEED 255
typedef struct context{
  bool tilt;
  bool bump;
  int status;
  int direction;
  byte speed1;
  byte speed2;
  unsigned long prevHbSeconds;
  unsigned long HbSeconds;
  unsigned long prevHb100Ms;
  unsigned long Hb100Ms;
  unsigned long prevHb10Ms;
  unsigned long Hb10Ms;

} CONTEXT;

typedef struct NotBounching{
  unsigned long seenHigh;
  unsigned long seenLow;
  uint8_t button;
  bool actualStatus;

}NOTBOUNCHING;

CONTEXT _context;
NOTBOUNCHING _startButton;
byte speed;
int dir = 1; 
void stateMachine(CONTEXT* ctx){
  static int mowstarted;
  static int waitclean;
  if(ctx->tilt && ctx->status != STATUS_ALARM && ctx->status != STATUS_RESETTABLE_ALARM){
     ctx->status = STATUS_ALARM;
  }
  
  switch(ctx->status){
    case STATUS_BOOT:
      if(ctx->HbSeconds<1){
        digitalWrite(BUZZER,HIGH);
      }
      if(ctx->HbSeconds == 1){
        digitalWrite(BUZZER,LOW);
        digitalWrite(ON_RED,HIGH);
      }
      if(ctx->HbSeconds == 2){
        digitalWrite(ON_RED,LOW);
        digitalWrite(ON_GREEN,HIGH);
      }
      if(ctx->HbSeconds == 3){
        digitalWrite(ON_GREEN,LOW);
        ctx->status=STATUS_IDLE;
      }
      break;
    case STATUS_IDLE:
      if(_startButton.actualStatus==1){
        ctx->status=STATUS_IDLE_READY;
      }
      break;
    case STATUS_IDLE_READY:
      if(_startButton.actualStatus==0){
        ctx->status=STATUS_ILIKETOMOWIT_IDLE;
      }
      break;
    case STATUS_ILIKETOMOWIT_IDLE:
      //just start when user is leaving the start button for safety
      if(_startButton.actualStatus==1){
        ctx->status=STATUS_ILIKETOMOWIT;
        if(ctx->direction==0){
          ctx->direction=1;
        }
        //start at zero speed
        analogWrite(MOTOR1_SPEED,0);
        analogWrite(MOTOR2_SPEED,0);
        ctx->speed1 = 0;
        ctx->speed2 = 0;
        digitalWrite(MOW,HIGH);
        mowstarted=ctx->HbSeconds;
        ctx->status = STATUS_ILIKETOMOWIT_WAITMOW;
      }
      break;
    case  STATUS_ILIKETOMOWIT_WAITMOW:
      if(ctx->HbSeconds-mowstarted>3){
        ctx->status = STATUS_ILIKETOMOWIT_WAIT2; //need to rest a little to avoid capturing noise generated by buzzer on sensors
        waitclean=ctx->HbSeconds;
        if(ctx->direction == 1){
          digitalWrite(MOTOR1_FWD,HIGH);
          digitalWrite(MOTOR2_FWD,HIGH);
          digitalWrite(MOTOR1_BWD,LOW);
          digitalWrite(MOTOR2_BWD,LOW);
        }else{
          digitalWrite(MOTOR1_FWD,LOW);
          digitalWrite(MOTOR2_FWD,LOW);
          digitalWrite(MOTOR1_BWD,HIGH);
          digitalWrite(MOTOR2_BWD,HIGH);
        }
      }
      break;
    case STATUS_ILIKETOMOWIT_WAIT2:
      if(ctx->HbSeconds-waitclean>=1){
        ctx->status = STATUS_ILIKETOMOWIT;
      }
      break; 
    case STATUS_ILIKETOMOWIT:
      if(_startButton.actualStatus==0){
        ctx->status=STATUS_IDLE;
        digitalWrite(MOTOR1_FWD,LOW);
        digitalWrite(MOTOR2_FWD,LOW);
        digitalWrite(MOTOR1_BWD,LOW);
        digitalWrite(MOTOR2_BWD,LOW);
        analogWrite(MOTOR1_SPEED,0);
        analogWrite(MOTOR2_SPEED,0);
        digitalWrite(MOW,LOW);
        ctx->speed1=0;ctx->speed2=0;

      }
      break;
    case STATUS_ALARM:
      
        digitalWrite(BUZZER,LOW);
        digitalWrite(MOTOR1_FWD,LOW);
        digitalWrite(MOTOR1_BWD,LOW);
        analogWrite(MOTOR1_SPEED,0);
        digitalWrite(MOTOR2_FWD,LOW);
        digitalWrite(MOTOR2_BWD,LOW);
        analogWrite(MOTOR2_SPEED,0);
        digitalWrite(MOW,LOW);
        ctx->speed1=ctx->speed2=0;
      //only when we have start button depressed we will accept 
      //a press to exit the alarm status.. button is 1 when depressed
      if(_startButton.actualStatus==1){
        ctx->status=STATUS_RESETTABLE_ALARM;
      }
    break;
    case STATUS_RESETTABLE_ALARM:
      if(_startButton.actualStatus==0){
        ctx->status=STATUS_IDLE;
        ctx->tilt=false;
        
      }
    break;
  }
}
void setup() {
   // Set Timer 0 prescaler to 8
  // 16 MHz clock / 8 (prescaler) / 256 (Timer Top) = 7812.5 Hz
  TCCR0B = (TCCR0B & 0xF8) | 0x02; 
  memset(&_context,0,sizeof(_context));
  memset(&_startButton,0,sizeof(NOTBOUNCHING));
  _startButton.button=START;
  _startButton.actualStatus=HIGH; //since is pull-up, we need to set logical state according to avoid false transitions
  Wire.begin();
  initAdxl345();
  Serial.begin(115200);
  pinMode(BUZZER,OUTPUT);
  pinMode(MOW,OUTPUT);
  pinMode(MOTOR1_FWD,OUTPUT);
  pinMode(MOTOR1_SPEED,OUTPUT);
  pinMode(MOTOR1_BWD,OUTPUT);
  pinMode(MOTOR2_FWD,OUTPUT);
  pinMode(MOTOR2_SPEED,OUTPUT);
  pinMode(MOTOR2_BWD,OUTPUT);
  pinMode(START,INPUT_PULLUP);
  pinMode(HOME,INPUT_PULLUP);
  pinMode(ON_RED,OUTPUT);
  pinMode(ON_GREEN,OUTPUT);
  pinMode(TAP, INPUT);
  attachInterrupt(digitalPinToInterrupt(TAP), handleTap, RISING);
}
bool accelReadable=false;
void loop() {
  updateHeartBeats(&_context);
  unbounch(&_startButton,&_context);
  stateMachine(&_context);
  
  if(_context.HbSeconds>=1){
    accelReadable = true;
  }
  if(accelReadable && _context.Hb100Ms%2 == 0){
    checkTilt(&_context);
  }
  if(_context.status>STATUS_BOOT && _context.Hb10Ms%2==0){
    
    updateHmi(&_context);
  }
  
  accelerate(&_context);
  if(_context.Hb100Ms%2==0){
    
    consumeAccelerometerInts();
    /*
    Serial.print("L=");
    Serial.print(analogRead(SENSOR_L));
    Serial.print("R=");
    Serial.println(analogRead(SENSOR_R));
    */
    Serial.println(_startButton.actualStatus);
  }
  /*
  if(millis()-prevTime>10){
    if(dir>0){
      digitalWrite(MOTOR2_FWD,HIGH);
      digitalWrite(MOTOR2_BWD,LOW);
    }else{
      digitalWrite(MOTOR2_FWD,LOW);
      digitalWrite(MOTOR2_BWD,HIGH);
    }
    prevTime=millis();
    speed+=dir;
    if(speed==255 || speed==0){
      dir=-dir;
    }
    analogWrite(MOTOR2_SPEED,speed);
    
  }*/
  
}
void consumeAccelerometerInts(){
   // must consume interrupts to re-enable
    Wire.beginTransmission(ACCELEROMETER);
    Wire.write(0x30);
    Wire.endTransmission(false);
    Wire.requestFrom(ACCELEROMETER, 1);
    
    if (Wire.available()) {
      byte source = Wire.read();
    }
}
void initAdxl345(){
  
  writeRegister(ACCELEROMETER,0x2D,8); //enable output
  writeRegister(ACCELEROMETER,0x2A,1); //TAP axes=Z
  writeRegister(ACCELEROMETER,0x21,60);//TAP duration 
  writeRegister(ACCELEROMETER,0x2F,0); //int map SINGLE tap on int 1
  writeRegister(ACCELEROMETER,0x1D,0x25); //threeshold tap
  writeRegister(ACCELEROMETER,0x2E,0x40); //int enable single tap
}
void writeRegister(uint8_t paddress,byte regAddress, byte val) {
  Wire.beginTransmission(paddress);
  Wire.write(regAddress);
  Wire.write(val);
  Wire.endTransmission();
}
void checkTilt(CONTEXT *ctx){
    static int spikes;
    int AX,AY,AZ;
    Wire.beginTransmission(ACCELEROMETER);
    Wire.write(0x32); // Start with register 0x32 (ACCEL_XOUT_H)
    Wire.endTransmission(false);
    Wire.requestFrom(ACCELEROMETER, 6, true); // Read 6 registers total, each axis value is stored in 2 registers
    AX = ( Wire.read() | Wire.read() << 8); // X-axis value
    AY = ( Wire.read() | Wire.read() << 8); // Y-axis value
    AZ = ( Wire.read() | Wire.read() << 8); // Z-axis value
    
    if(AY>TILT_Y && !ctx->tilt){
      spikes++;
    }else{
      spikes = 0;
    }
    if(spikes==10){
      ctx->tilt = true;
      spikes = 0;
    }
}
//interrupt handler for TAP detection
void handleTap(){
  _context.bump=true;
}
void updateHeartBeats(CONTEXT *ctx){
  //heach hb LSB logic vaue has a period of the corresponding duration
  int m = millis()/8;
  if(m-ctx->prevHbSeconds>500){
    ctx->prevHbSeconds=m;
    ctx->HbSeconds++;
  }
  if(m-ctx->prevHb100Ms>50){
    ctx->prevHb100Ms=m;
    ctx->Hb100Ms++;
  }
  if(m-ctx->prevHb10Ms>5){
    ctx->prevHb10Ms=m;
    ctx->Hb10Ms++;
  }

}
//handle engine acceleration,to avoid abrupt starts
void accelerate(CONTEXT* ctx){
  if( ctx->status==STATUS_ILIKETOMOWIT && ctx->speed1<MAX_SPEED ){
    if(ctx->Hb100Ms%6==0){
      ctx->speed1++;
      analogWrite(MOTOR1_SPEED,ctx->speed1);
    }
    
  }
  if( ctx->status==STATUS_ILIKETOMOWIT && ctx->speed2<MAX_SPEED ){
    if(ctx->Hb100Ms%6==0){
      ctx->speed2++;
      analogWrite(MOTOR2_SPEED,ctx->speed2);
    }
    
  }
}
void unbounch(NOTBOUNCHING* button,CONTEXT* ctx){
  int cs = digitalRead(button->button);
  if(cs ==HIGH && button->seenHigh==0){
    button->seenHigh=ctx->Hb10Ms;
  }
  if(cs ==LOW && button->seenLow==0){
    button->seenLow=ctx->Hb10Ms;
  }
  if(cs == HIGH ){
    button->seenLow=0;
  }
  if(cs == LOW ){
    button->seenHigh=0;
  }
  if(button->seenHigh!=0 && ctx->Hb10Ms-button->seenHigh>9){
    button->actualStatus=HIGH;
  }
  if(button->seenLow!=0 && ctx->Hb10Ms-button->seenLow>9){
    button->actualStatus=LOW;
  }
}
void updateHmi(CONTEXT *ctx){
  digitalWrite(BUZZER,ctx->tilt && (ctx->HbSeconds %2 == 0) ||
                    ctx->status==STATUS_ILIKETOMOWIT_WAITMOW
    ? HIGH:LOW);
  digitalWrite(ON_GREEN,ctx->status==STATUS_ILIKETOMOWIT_IDLE && (ctx->HbSeconds %2 == 0 || STATUS_ILIKETOMOWIT)  ? HIGH:LOW);
  digitalWrite(ON_RED,ctx->status==STATUS_RESETTABLE_ALARM && (ctx->HbSeconds%2 == 0|| STATUS_ALARM)  ? HIGH:LOW);
}